if (!surface_exists(surf))
    surf = surface_view_create()
surface_default_setup(surf)
draw_sprite_ext(sp_wellDone, 0, 191, (32 + wave(-8, 8, 3.8)), wellDoneScale, wellDoneScale, wellDoneRotation, c_white, 1)
draw_set_font(global.fontPointCounter)
draw_set_color(c_white)
draw_set_alignment(0, 0)
draw_sprite(sp_casinoChipHUD, sprite_get_current_subimage(sp_casinoChipHUD), (282 + statsOffset), 95)
draw_sprite(sp_pointCounter, 0, (293 + statsOffset), 85)
draw_text((296 + statsOffset), 92, string_replace_all(string_format(ob_treasureCounter.actualScore, 6, 0), " ", "0"))
draw_sprite_ext(sp_casinoChipRed, (sprite_get_current_subimage(sp_casinoChipRed)), (282 + statsOffset), 161, chipScale, chipScale, 0, c_white, 1)
if (chipScale > 1)
    chipScale -= 0.25
draw_sprite(sp_pointCounterTotal, 0, (293 + statsOffset), 151)
draw_text((296 + statsOffset), 158, string_replace_all(string_format(totalScoreDisplayed, 6, 0), " ", "0"))
draw_set_font(global.fontMain)
draw_text((270 + statsOffset), 134, "TOTAL@")
if ob_timeAttackManager.enabled
{
    draw_text((270 + statsOffset), 181, "FINAL TIME")
    draw_set_font(fn_menu)
    var _outlineBaseSurf = surface_create(128, 32)
    surface_set_target(_outlineBaseSurf)
    draw_clear_alpha(c_black, 0)
    draw_text(1, 1, frames_to_timer_string(ob_timeAttackManager.time, 1))
    surface_reset_target()
    var _outlineSurf = surface_outline_create(_outlineBaseSurf)
    draw_surface(_outlineBaseSurf, (270 + statsOffset), 198)
    draw_surface_ext(_outlineSurf, (270 + statsOffset), 198, 1, 1, 0, c_black, 1)
    surface_free(_outlineBaseSurf)
    surface_free(_outlineSurf)
}
spiritYPosition = ((169 + statsOffset) + wave(-4, 4, 4.6))
draw_sprite(sp_spiritSlot, 0, 157, (169 + statsOffset))
draw_sprite(sp_vinylSlot, 0, 203, ((183 + statsOffset) + wave(-4, 4, 4.6)))
if ob_treasureManager.b_vinylCollected
    draw_sprite(sp_vinyl, 0, 203, ((183 + vinylOffset) + wave(-4, 4, 4.6)))
for (var i = 3; i >= 0; i -= 1)
    draw_sprite(sp_lifeCounterHeart, (ob_treasureManager.finalHP > i ? 0 : 1), ((healthPos.x + (16 * i)) - statsOffset), healthPos.y)
with (ob_beetParticle)
    draw_self()
gpu_set_blendmode(bm_normal)
surface_reset_target()
draw_surface(surf, camera_get_view_x(view_camera[0]), camera_get_view_y(view_camera[0]))
