if ((!timerActive) || (!enabled) || 0)
    return;
draw_set_alignment(0, 0)
draw_set_font(fn_menu)
draw_set_color(c_white)
var _drawPos = new vector2(((camera_get_view_x(view_camera[0]) + 384) - 58), ((camera_get_view_y(view_camera[0]) + 216) - 17))
var _outlineBaseSurf = surface_create(128, 32)
surface_set_target(_outlineBaseSurf)
draw_clear_alpha(c_black, 0)
draw_text(1, 1, frames_to_timer_string(time, 1))
surface_reset_target()
var _outlineSurf = surface_outline_create(_outlineBaseSurf)
draw_surface(_outlineBaseSurf, _drawPos.x, _drawPos.y)
draw_surface_ext(_outlineSurf, _drawPos.x, _drawPos.y, 1, 1, 0, c_black, 1)
surface_free(_outlineBaseSurf)
surface_free(_outlineSurf)
