global.p_system = part_system_create()
part_system_depth(global.p_system, -6000)
global.p_systemBG = part_system_create()
part_system_depth(global.p_systemBG, 1400)
global.particleFootDust = part_type_create()
part_type_sprite(global.particleFootDust, sp_footdust_particle, 1, 0, 0)
part_type_life(global.particleFootDust, 16, 16)
global.particleLandingDust = part_type_create()
part_type_sprite(global.particleLandingDust, sp_landing_particle, 1, 0, 0)
part_type_life(global.particleLandingDust, 20, 20)
global.particleAssBlast = part_type_create()
part_type_sprite(global.particleAssBlast, sp_assblast_particle, 1, 0, 0)
part_type_life(global.particleAssBlast, 24, 24)
global.particleAssBlast2 = part_type_create()
part_type_sprite(global.particleAssBlast2, sp_assblast_particle2, 1, 0, 0)
part_type_life(global.particleAssBlast2, 28, 28)
global.particleClutchDust = part_type_create()
part_type_sprite(global.particleClutchDust, sp_clutchDust_particle, 1, 0, 0)
part_type_life(global.particleClutchDust, 10, 10)
global.particleCrate = part_type_create()
part_type_sprite(global.particleCrate, sp_crate_particle, 0, 0, 1)
part_type_life(global.particleCrate, 60, 60)
global.particleSupport = part_type_create()
part_type_sprite(global.particleSupport, sp_support_particle, 0, 0, 1)
part_type_life(global.particleSupport, 60, 60)
global.particleBrick = part_type_create()
part_type_sprite(global.particleBrick, sp_brick_particle, 0, 0, 1)
part_type_life(global.particleBrick, 60, 60)
global.particleFootDustVB = part_type_create()
part_type_sprite(global.particleFootDustVB, sp_footdust_particleVB, 1, 0, 0)
part_type_life(global.particleFootDustVB, 16, 16)
global.particleLandingDustVB = part_type_create()
part_type_sprite(global.particleLandingDustVB, sp_landing_particleVB, 1, 0, 0)
part_type_life(global.particleLandingDustVB, 16, 16)
global.particleAssBlastVB = part_type_create()
part_type_sprite(global.particleAssBlastVB, sp_assblast_particleVB, 1, 0, 0)
part_type_life(global.particleAssBlastVB, 24, 24)
global.particleAssBlast2VB = part_type_create()
part_type_sprite(global.particleAssBlast2VB, sp_assblast_particle2VB, 1, 0, 0)
part_type_life(global.particleAssBlast2VB, 28, 28)
global.particleClutchDustVB = part_type_create()
part_type_sprite(global.particleClutchDustVB, sp_clutchDust_particleVB, 1, 0, 0)
part_type_life(global.particleClutchDustVB, 10, 10)
global.particleRestHouse = part_type_create()
part_type_sprite(global.particleRestHouse, sp_resthouse_particle, 0, 0, 1)
part_type_life(global.particleRestHouse, 60, 60)
global.particleConcrete = part_type_create()
part_type_sprite(global.particleConcrete, sp_concrete_gibs, 0, 0, 1)
part_type_life(global.particleConcrete, 60, 60)
global.particleGlassBreak = part_type_create()
part_type_sprite(global.particleGlassBreak, sp_glassbreak_particle, 0, 0, 1)
part_type_life(global.particleGlassBreak, 60, 60)
global.particleHitSmack = part_type_create()
part_type_sprite(global.particleHitSmack, sp_enemySmack_particle, 1, 0, 0)
part_type_life(global.particleHitSmack, 15, 15)
global.particleFootDustBG = part_type_create()
part_type_sprite(global.particleFootDustBG, sp_footdust_particleBG, 1, 0, 0)
part_type_life(global.particleFootDustBG, 16, 16)
global.particleLandingDustBG = part_type_create()
part_type_sprite(global.particleLandingDustBG, sp_landing_particleBG, 1, 0, 0)
part_type_life(global.particleLandingDustBG, 20, 20)
global.particleAssBlastBG = part_type_create()
part_type_sprite(global.particleAssBlastBG, sp_assblast_particleBG, 1, 0, 0)
part_type_life(global.particleAssBlastBG, 24, 24)
global.particleAssBlast2BG = part_type_create()
part_type_sprite(global.particleAssBlast2BG, sp_assblast_particle2BG, 1, 0, 0)
part_type_life(global.particleAssBlast2BG, 28, 28)
global.particleClutchDustBG = part_type_create()
part_type_sprite(global.particleClutchDustBG, sp_clutchDust_particleBG, 1, 0, 0)
part_type_life(global.particleClutchDustBG, 10, 10)
global.particleGlassBreakBG = part_type_create()
part_type_sprite(global.particleGlassBreakBG, sp_glassbreak_particleBG, 0, 0, 1)
part_type_life(global.particleGlassBreakBG, 60, 60)
global.particleCrateBG = part_type_create()
part_type_sprite(global.particleCrateBG, sp_crate_particleBG, 0, 0, 1)
part_type_life(global.particleCrateBG, 60, 60)
global.particleSupportBG = part_type_create()
part_type_sprite(global.particleSupportBG, sp_support_particleBG, 0, 0, 1)
part_type_life(global.particleSupportBG, 60, 60)
global.particleBrickBG = part_type_create()
part_type_sprite(global.particleBrickBG, sp_brick_particleBG, 0, 0, 1)
part_type_life(global.particleBrickBG, 60, 60)
global.particleRestHouseBG = part_type_create()
part_type_sprite(global.particleRestHouseBG, sp_resthouse_particleBG, 0, 0, 1)
part_type_life(global.particleRestHouseBG, 60, 60)
global.particleVinyl = part_type_create()
part_type_sprite(global.particleVinyl, sp_vinylParticle, 0, 0, 1)
part_type_life(global.particleVinyl, 60, 60)
